### PR TITLE
Modernize chapter 4

### PR DESCRIPTION
**Pull request by mittinatten**

### CODE REVIEW

**Comment by mittinatten** [comment]
Sorry this PR was meant for our fork.

**Comment by mamund** [comment]
no problem.

happy to see the projects are in use. let me know if you have feedback/comments along the way.

in the future, feel free to send any PRs that would improve the examples

cheers

**Comment by mittinatten** [comment]
Yes, that’s the plan! (I think my colleague Einar has already been in touch
with you) This particular PR is just an intermediate step.

ons 2 feb. 2022 kl. 16:47 skrev Mike Amundsen ***@***.***>:

**Comment by mamund** [comment]
all sounds fine. thanks.

**Pull request closed without merging**
